language: ruby
rvm:
 - 1.8.7
 - 2.0.0

script: "bundle exec rake spec"

branches:
  only:
      - master
      - /^issues\/.*$/

notifications:
  email:
    - arusso@berkeley.edu

env:
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER="yes"
